# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc "gg (Gopher Glide) — fast, stage-based HTTP load-testing tool with behavioral snapshot support"
  homepage "https://github.com/shyam-s00/gopher-glide"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shyam-s00/gopher-glide/releases/download/v0.7.0/gg-0.7.0-darwin-arm64.tar.gz"
      sha256 "622e42b188fe041bc79aab1bb50472636cc3cf5ae43e6f2acf0e930da5d8375d"

      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyam-s00/gopher-glide/releases/download/v0.7.0/gg-0.7.0-linux-amd64.tar.gz"
      sha256 "fe36365961dcd29d938f21bb647a31a4c54e56dfeeb13a676a5908768c8dddf6"
      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  test do
    system "#{bin}/gg", "--help"
  end
end
