# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc "gg (Gopher Glide) — fast, stage-based HTTP load-testing tool with behavioral snapshot support"
  homepage "https://github.com/shyam-s00/gopher-glide"
  version "0.9.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shyam-s00/gopher-glide/releases/download/v0.9.3/gg-v0.9.3-darwin-arm64.tar.gz"
      sha256 "5314c267e2e41aa2aab92e27bab58508c523d6037b034e54308b3d318c930a7f"

      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyam-s00/gopher-glide/releases/download/v0.9.3/gg-v0.9.3-linux-amd64.tar.gz"
      sha256 "9e3919bd06afe9c68379e7cf138e86a3a769ba6621261047bf727bf5be8f098b"
      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  test do
    system "#{bin}/gg", "--help"
  end
end
