# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc "gg (Gopher Glide) — fast, stage-based HTTP load-testing tool with behavioral snapshot support"
  homepage "https://github.com/shyam-s00/gopher-glide"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shyam-s00/gopher-glide/releases/download/v0.9.2/gg-v0.9.2-darwin-arm64.tar.gz"
      sha256 "f7de4ee4f2ab529bb608bcce4e68856a94bad061d336258caebb239eb2ac736c"

      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyam-s00/gopher-glide/releases/download/v0.9.2/gg-v0.9.2-linux-amd64.tar.gz"
      sha256 "db089d2c6815e679e49dd030902808cc4fed8eaf304c1be77b8ba18fb63a9bda"
      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  test do
    system "#{bin}/gg", "--help"
  end
end
